### ISSUE TITLE
Support overwriting part of an ephemeris/orientation data

### ISSUE THREAD

**Issue by ChristopherRabotin** [nyx-space/anise#21]
There is a use case where a user may wish to load a smaller spacecraft ephemeris and have ANISE automatically switch to that one where possible. In SPICE this is handled by order to loading (`furnsh`). This helps in creation operational kernels. In the following example, let `PREV` be the previous spacecraft ephemeris, `NEW` be the new one from a new orbit determination solution.

```
Query     t_0  t_1 t_2 ...    t_k
                |      |     |            |
NEW        |   ---------------   |
PREV     -------------------------
```

In this use case, `NEW` does not have any data for `t_0` or `t_k`, but it does for `t_1` and `t_2`. So for `t_0` and `t_k` querying, SPICE returns the data from PREV. But for a query on `t_1` or `t_2` SPICE returns the data from the `NEW` ephemeris.

This simplest solution here is to prevent loading two ephemeris/orientation data with the same name. If we support loading both, then there could be some confusion (where does _this_ data point come from) and it's complicated to store both given how the look up table is setup. At the same time, I definitely see a use-case where one might want this: updating an ephemeris after an OD solution for example. _But_ that use-case would probably be better handled through the `anise merge` command (or `anise_ctx.merge(anise_ctx_2)` via the rust API).

@pwnorbitals , what do you think should be the behavior?

**Comment by pwnorbitals** [comment]
Interesting. I definitely see a use-case where we load multiple data sources, make a query at a given timestamp and want to know which data source it comes from. Imo this could be handled by separate multi-context query functions with order-sensitive arguments, ex : `anise::multi_query(anise::QueryType::Orientation, timeOfEvent, &[anise_ctx_1, anise_ctx_2, anise_ctx_3])`. The result would be from `ctx_1` if found there, otherwise from `ctx_2` and `ctx_3` in order. Also we could have a number of these `multi` functions with different variants (maybe one to pick the data point with the lowest covariance)... Just throwing ideas at the wall :)

**Comment by ChristopherRabotin** [comment]
Closing this because ANISE currently works exactly like SPICE where the order of loading the data matters in the search of a valid ephemeris or orientation segment.
