### ISSUE TITLE
0.4.2 (Build.rs) causes cargo docs to fail to build

### ISSUE THREAD

**Issue by gwbres** [nyx-space/anise#289]
Hello,

we're having an unfortunate and unpredictible little issue. What happens on line 31 in the Build.rs script prevents to generate the documentation of any library that depends on ANISE 0.4.2. Apparently because this runs inside a docker without write permission. [Build failure log example](https://docs.rs/crate/gnss-rtk/0.6.0/builds/1313770). We have two options

- either rework the script to allow this step to fail, which may be tedious to do
- try to see if we can detect that it is a `documentation` run, not a normal run, and this could be totally avoided

[Consequence](https://docs.rs/crate/gnss-rtk/latest)

**Comment by ChristopherRabotin** [comment]
Hello,

I have noticed this issue too in the tests in CI. The crux of the problem is that sometimes, the request to download the files from the public storage server fails. That server is a static server running on the Google Cloud Storage, and I have no idea why it would fail. When it happens in ci, I can just rerun the test, but it's very frustrating.

I'll look more into it, but at this stage, I really have no leads as to why Google won't server the files quickly and reliably.

**Comment by gwbres** [comment]
hum, weird. As far as CI/CD goes, we can always re-run, but I understand, we tend to have heavy libraries here, and the process is quite lengthy. Maybe we should simply define [in the ANISE metadata](https://docs.rs/about/metadata), to never document with the embed_ephem, and we're good to go

**Comment by ChristopherRabotin** [comment]
Oh, you're entirely right. I had misread the error. Yes, I think that by simply not building the documentation with embed_ephem, then it'll fix the read only error. This is different from the error I have seen too often than I would hope.

**Comment by gwbres** [comment]
You said the error might be induced by gnss-rtk, but if that is the case, then I totally do not understand.
I'm able to build the docs for this crate myself, IMO the issue is solely related to the job that dockerizes crates.io.
And the issues apparently only happen since we introduced the `embed_ephem` feature and because that job is deployed with said feature being active
